### ISSUE TITLE
[Bug] Illegal access in openjdk 12

### ISSUE THREAD

**Issue by tom7t** [funcool/buddy-core#65]
Did a search on this repository and wasn't able to find anything matching "illegal access". Just tried updating a project to use openjdk 12, and it looks like bouncy castle isn't playing nice. 

```clojure
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:<path-to-my-project>) to constructor sun.security.provider.Sun()
	at org.bouncycastle.jcajce.provider.drbg.DRBG.findSource(Unknown Source)
	at org.bouncycastle.jcajce.provider.drbg.DRBG.<clinit>(Unknown Source)
	at org.bouncycastle.jcajce.provider.drbg.DRBG$Mappings.configure(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
	at buddy.core.dsa__init.load(Unknown Source)
	at buddy.core.dsa__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:415)
	at clojure.lang.RT.classForName(RT.java:2207)
	at clojure.lang.RT.classForName(RT.java:2216)
	at clojure.lang.RT.loadClassForName(RT.java:2235)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
```

This is when building the project using lein uberjar. I'm using the following dependencies in the file that is invoking buddy functions:

```clojure
[buddy.sign.jwt :as jwt]
[buddy.hashers :as bh]
```

**Comment by niwinz** [comment]
BC dependency is signed, so if you create uberjars the signature is no longer matches. You can't create uberjars with BC dependency. If you stull want uberjar, you need to exclude bouncycastle dep and provide it separatelly in the classpath.
